// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsjylf5THJd-mqlHRr6X2NvbO2jbuaZDs',
    appId: '1:170485151920:web:b729fe794ccb4fbfb46375',
    messagingSenderId: '170485151920',
    projectId: 'finstagram-cf2b5',
    authDomain: 'finstagram-cf2b5.firebaseapp.com',
    storageBucket: 'finstagram-cf2b5.appspot.com',
    measurementId: 'G-0ECEZ388FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADc0uFe2B3Np_Bj1AtO88shDmqQv3w1Xs',
    appId: '1:170485151920:android:27632532fcb2c625b46375',
    messagingSenderId: '170485151920',
    projectId: 'finstagram-cf2b5',
    storageBucket: 'finstagram-cf2b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl3hF41XvebX_nvaZGx33vaxevoqSlV5A',
    appId: '1:170485151920:ios:46e7eed4d5e1f749b46375',
    messagingSenderId: '170485151920',
    projectId: 'finstagram-cf2b5',
    storageBucket: 'finstagram-cf2b5.appspot.com',
    iosBundleId: 'com.example.finstagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl3hF41XvebX_nvaZGx33vaxevoqSlV5A',
    appId: '1:170485151920:ios:46e7eed4d5e1f749b46375',
    messagingSenderId: '170485151920',
    projectId: 'finstagram-cf2b5',
    storageBucket: 'finstagram-cf2b5.appspot.com',
    iosBundleId: 'com.example.finstagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsjylf5THJd-mqlHRr6X2NvbO2jbuaZDs',
    appId: '1:170485151920:web:8a44cc634c925f08b46375',
    messagingSenderId: '170485151920',
    projectId: 'finstagram-cf2b5',
    authDomain: 'finstagram-cf2b5.firebaseapp.com',
    storageBucket: 'finstagram-cf2b5.appspot.com',
    measurementId: 'G-K2EK9QK7GG',
  );
}
